- name: Install xfce4 packages
  become: true
  apt:
    state: latest
    name:
      - xfce4
      - xfce4-whiskermenu-plugin
      - xfce4-systemload-plugin
      - xfce4-netload-plugin
      - xfce4-taskmanager
      - xfce4-xkb-plugin
      - thunar
      - thunar-archive-plugin
      - ristretto
      - papirus-icon-theme

# HiDPI settings
- name: Set xfce4 DPI
  xfconf:
    channel: xsettings
    property: /Xft/DPI
    value_type: int
    value: 192

- name: Set xresources DPI
  blockinfile:
    path: ~/.Xresources
    create: true
    block: |
      Xft.dpi: 192
    marker: '!! {mark} ANSIBLE MANAGED BLOCK'

- name: Set HiDPI scaling variables for GTK, QT and JAVA
  become: true
  blockinfile:
    path: /etc/environment
    create: true
    block: |
      JAVA_TOOL_OPTIONS=-Dsun.java2d.uiScale=2
      GDK_SCALE=2
      GDK_DPI_SCALE=0.5
      QT_AUTO_SCREEN_SCALE_FACTOR=1
    marker: '## {mark} ANSIBLE MANAGED BLOCK'

- name: Add autoscale command (xscale)
  become: true
  copy:
    dest: /usr/local/bin/xscale
    content: |
      #!/bin/sh
      xrandr --output "$(xrandr --query | awk '/ connected/{print $1; exit}')" --auto
    mode: 0755

# Theme settings
- name: Install nordic theme
  become: true
  unarchive:
    src: Nordic.zip
    dest: /usr/share/themes/

- name: Configure XFCE theme, desktop and window manager settings
  xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: "{{ item.type }}"
  loop:
    # Theme settings
    - { channel: xsettings, property: /Net/ThemeName, value: Nordic, type: string }
    - { channel: xfwm4, property: /general/theme, value: Nordic, type: string }
    - { channel: xsettings, property: /Xfce/SyncThemes, value: true, type: bool }
    - { channel: xsettings, property: /Net/IconThemeName, value: Papirus-Dark, type: string }
    - { channel: xsettings, property: /Gtk/CursorThemeName, value: Adwaita, type: string }
    # Desktop settings
    - { channel: xfce4-desktop, property: /desktop-icons/style, value: 0, type: int }
    - { channel: xfce4-desktop, property: /desktop-menu/show, value: false, type: bool }
    - { channel: xfce4-desktop, property: /windowlist-menu/show, value: false, type: bool }
    - { channel: xfce4-desktop, property: /backdrop/screen0/monitorVirtual-1/workspace0/color-style, value: 0, type: int }
    - { channel: xfce4-desktop, property: /backdrop/screen0/monitorVirtual-1/workspace0/image-style, value: 0, type: int }
    - { channel: xfce4-desktop, property: /backdrop/screen0/monitorVirtual-1/workspace0/rgba1, value: [0.10196078431372549, 0.10196078431372549, 0.11372549019607843, 1], type: double, force_array: true }
    - { channel: keyboard-layout, property: /Default/XkbDisable, value: false, type: bool }
    - { channel: keyboard-layout, property: /Default/XkbOptions/Group, value: grp:alt_shift_toggle, type: string }
    # Window manager settings
    - { channel: xfwm4, property: /general/button_layout, value: CHM|, type: string }
    - { channel: xfwm4, property: /general/title_alignment, value: center, type: string }
    - { channel: xfwm4, property: /general/cycle_workspaces, value: true, type: bool }
    - { channel: xfwm4, property: /general/activate_action, value: switch, type: string }
    - { channel: xfwm4, property: /general/mousewheel_rollup, value: false, type: bool }
    - { channel: xfwm4, property: /general/scroll_workspaces, value: false, type: bool }
    - { channel: xfwm4, property: /general/zoom_desktop, value: false, type: bool }
    - { channel: xfwm4, property: /general/zoom_pointer, value: false, type: bool }
    - { channel: xfce4-appfinder, property: /hide-window-decorations, value: true, type: bool }
    - { channel: xfce4-appfinder, property: /close-on-focus-lost, value: true, type: bool }
    - { channel: xfce4-appfinder, property: /sort-by-frecency, value: true, type: bool }

- name: Change shortcuts
  shell: |
    xfconf-query -c xfce4-keyboard-shortcuts -p '/xfwm4/custom/<Primary>Delete' -r -R

- name: Install panel plugins
  become: true
  apt:
    state: latest
    name:
      - xfce4-whiskermenu-plugin
      - xfce4-systemload-plugin
      - xfce4-netload-plugin
      - xfce4-taskmanager
      - xfce4-xkb-plugin

- name: Remove default panel directory
  file:
    path: ~/.config/xfce4/panel
    state: absent

- name: Ensure panel directory exists
  file:
    path: ~/.config/xfce4/panel
    state: directory
    recurse: true

- name: Copy panel configuration
  copy:
    src: panel/
    dest: ~/.config/xfce4/panel/
    mode: 0644
    directory_mode: 0755

- name: Copy panel configuration
  copy:
    src: xfce4-panel.xml
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml

- name: Copy lightdm-gtk-greeter.conf
  become: true
  copy:
    src: lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf

# Fonts
- name: Install fonts
  become: true
  apt:
    state: latest
    name:
      - fonts-jetbrains-mono 
      - fonts-noto 
      - fonts-recommended

- name: Set font settings
  xfconf:
    channel: xsettings
    property: /Gtk/FontName
    value_type: string
    value: Noto Sans 10
  xfconf:
    channel: xsettings
    property: /Gtk/MonospaceFontName
    value_type: string
    value: JetBrains Mono NL 12
