- name: Copy interfaces file
  become: true
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Install network-manager
  become: true
  apt:
    state: latest
    name:
      - network-manager-gnome
      - network-manager-openvpn-gnome
      - network-manager-openconnect

- name: Disable networking.service
  become: true
  systemd:
    name: networking.service
    enabled: no
    state: stopped

- name: Enable NetworkManager
  become: true
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Install systemd-resolved
  become: true
  apt:
    state: latest 
    name:
      - systemd-resolved
